// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=TiledCauldron
maven_group=gisellevonbingen.tiled_cauldron
mod_id=tiled_cauldron
mod_version=6.1
mod_name=Tiled Cauldron
mod_description=
mod_license=MIT
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/tiled-cauldron
mod_source=https://github.com/gisellevonbingen-Minecraft/TiledCauldron
mod_issues=https://github.com/gisellevonbingen-Minecraft/TiledCauldron/issues

// Minecraft, Mod Loader
mc_version=1.21.11
neoforge_loader_version=4
neoforge_api_version=21.11.0-beta
neoforge_api_version_range=[21.11.0-beta,)
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=BLEEDING-SNAPSHOT
neogradle.subsystems.conventions.sourcesets.enabled=false

// Implementation
mekanism_version=10.7.11.76
mekanism_version_range=[10.7.11,)

// Runtime Only
jei_version=19.21.0.247
