modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-TiledCauldron/issues"

[[mods]]
    modId="tiled_cauldron"
    version="${file.jarVersion}"
    displayName="Tiled Cauldron"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tiled-cauldron"
    authors="gisellevonbingen"
    description='''Connect pipe to Cauldron'''

[[dependencies.tiled_cauldron]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tiled_cauldron]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"
